dist: trusty
sudo: false

language: cpp
os: linux

#===---------------------------------------------------------------------------------------------===
#   Environment
#===---------------------------------------------------------------------------------------------===

# APT packages shared by all configurations 
addons:
  apt:
    sources: 
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - gcc-6
      - g++-5
      - gcc-5

matrix:
  # Linux GCC 5
  - os: linux
    compiler: gcc
    env: 
      - CXX_COMPILER=g++-5 
      - CXX_COMPILER=gcc-5 
  
  # Linux GCC 6
  - os: linux
    compiler: gcc
    env: 
      - CXX_COMPILER=g++-6 
      - CXX_COMPILER=gcc-6 


# Set directories to cache
cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/deps/cmake-3.6.1

#===---------------------------------------------------------------------------------------------===
#   Installing (external dependencies)
#===---------------------------------------------------------------------------------------------===

install:
  # Create deps dir if not existing
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR}
  
  - ls
  - echo ${CXX_COMPILER}
  - echo ${C_COMPILER}

  # Make sure CXX and C are set correctly for Linux builds
  - if [[ "${CXX_COMPILER}" != "" ]]; then export CXX=${CXX_COMPILER}; fi
  - if [[ "${C_COMPILER}" != "" ]]; then export CC=${C_COMPILER}; fi
  
  # Make sure CMAKE_BUILD_TYPE is correctly set
  - if [[ "${CONFIG}" != "" ]]; then export CMAKE_BUILD_TYPE=${CONFIG}; fi

  # Start building external dependencies
  - pushd $(pwd)
  - cd ${DEPS_DIR}

  # Install CMake 3.6.1
  - |
    CMAKE_DIR=${DEPS_DIR}/cmake-3.6.1
    if [[ -z "$(ls -A ${CMAKE_DIR})" ]]; then
     travis_retry wget --quiet https://cmake.org/files/v3.6/cmake-3.6.1.tar.gz
     tar xfz cmake-3.6.1.tar.gz
     (cd cmake-3.6.1 && ./configure --prefix=${CMAKE_DIR}/install && make install)
    fi
    export PATH="${CMAKE_DIR}/install/bin:${PATH}"

  - popd


#===---------------------------------------------------------------------------------------------===
#   Building
#===---------------------------------------------------------------------------------------------=== 

before_script:
  # Setup the X-Server and initialize display of 1280x1024x16
  - export DISPLAY=:99.0
  - |
    /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile       \
                            --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16
  - sleep 3

  - cmake --version
  - mkdir build

#===---------------------------------------------------------------------------------------------===
#   Testing
#===---------------------------------------------------------------------------------------------=== 

script:
  - pushd $(pwd)
  - cd build


notifications:
  on_success: never
  on_failure: never