dist: trusty
sudo: false

language: c++

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-3.9
      - llvm-toolchain-trusty-4.0
    packages: &global_packages
      - g++-5
      - gcc-5
      - g++-6
      - gcc-6
      # - clang-3.9
      # - clang++-3.9
      # - clang-4.0
      # - clang++-4.0

      - ccache
      - libtbb-dev

      # OpenCV deps
      - libjpeg-dev 
      - libpng12-dev 
      - libtiff4-dev 
      - libjasper-dev 

      # glfw3 deps
      - xorg-dev 
      - libglu1-mesa-dev
      - libx11-6
      - libxcursor1
      - libxi6
      - libxinerama1
      - libxrandr2
      - libxxf86vm1

      # backward deps
      - libdw-dev

os:
  - linux

env:
  global:
    - SCRIPT_DIR=${TRAVIS_BUILD_DIR}/scripts/travis
    - CACHE_DIR=${TRAVIS_BUILD_DIR}/deps/install
    - BOOST_VERSION=1.63.0
    - CMAKE_VERSION=3.8.1
    - GLBINDING_VERSION=2.1.1
    - OPENCV_VERSION=3.2.0

jobs:
  include:
    - stage: Prepare Cache
      compiler: gcc
      script: |
        bash ${SCRIPT_DIR}/driver-install.sh -i ${CACHE_DIR}                                       \
             -b cmake,boost,glbinding,opencv
      addons:
        apt:
          << : *global_packages
          ? clang-3.9 
          ? clang++-3.9

    # # Linux GCC 5.4 (Release)
    # - stage: Test
    #   compiler: gcc
    #   env: CONFIG=Release CXX_COMPILER=g++-5 C_COMPILER=gcc-5
    #   script: bash ${SCRIPT_DIR}/driver-test.sh
    
    # # Linux GCC 5.4 (RelWithDebInfo)
    # - stage: Test
    #   compiler: gcc
    #   env: CONFIG=RelWithDebInfo CXX_COMPILER=g++-5 C_COMPILER=gcc-5
    #   script: bash ${SCRIPT_DIR}/driver-test.sh

    # # Linux GCC 6.3 (Release)
    # - stage: Test
    #   compiler: gcc
    #   env: CONFIG=Release CXX_COMPILER=g++-6 C_COMPILER=gcc-6
    #   script: bash ${SCRIPT_DIR}/driver-test.sh
    
    # # Linux GCC 6.3 (RelWithDebInfo)
    # - stage: Test
    #   compiler: gcc
    #   env: CONFIG=RelWithDebInfo CXX_COMPILER=g++-6 C_COMPILER=gcc-6
    #   script: bash ${SCRIPT_DIR}/driver-test.sh

    # # Clang 3.9 (Release)
    # - stage: Test
    #   compiler: clang
    #   env: CONFIG=Release CXX_COMPILER=clang++-3.9 C_COMPILER=clang-3.9
    #   script: bash ${SCRIPT_DIR}/driver-test.sh

    # # Clang 3.9 (RelWithDebInfo)
    # - stage: Test
    #   compiler: clang
    #   env: CONFIG=RelWithDebInfo CXX_COMPILER=clang++-3.9 C_COMPILER=clang-3.9
    #   script: bash ${SCRIPT_DIR}/driver-test.sh

    # # Clang 4.0 (Release)
    # - stage: Test
    #   compiler: clang
    #   env: CONFIG=Release CXX_COMPILER=clang++-4.0 C_COMPILER=clang-4.0
    #   script: bash ${SCRIPT_DIR}/driver-test.sh

    # # Clang 4.0 (RelWithDebInfo)
    # - stage: Test
    #   compiler: clang
    #   env: CONFIG=RelWithDebInfo CXX_COMPILER=clang++-4.0 C_COMPILER=clang-4.0
    #   script: bash ${SCRIPT_DIR}/driver-test.sh

cache:
  directories:
    - ${CACHE_DIR}/boost-${BOOST_VERSION}
    - ${CACHE_DIR}/glbinding-${GLBINDING_VERSION}
    - ${CACHE_DIR}/opencv-${OPENCV_VERSION}
    - ${CACHE_DIR}/llvm-${LLVM_VERSION}

notifications:
  on_success: never
  on_failure: never