dist: trusty
sudo: false

language: c++

#===---------------------------------------------------------------------------------------------===
#   Environment
#===---------------------------------------------------------------------------------------------===

# APT packages shared by all configurations 
addons:
  apt:
    sources: 
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - gcc-5

os:
  - linux

env:
  global:
    CMAKE_VERSION=3.6.1

matrix:
  include:
    # Linux GCC 5.4 (Release)
    - os: linux
      compiler: gcc
      env: CONFIG=Release CXX_COMPILER=g++-5 C_COMPILER=gcc-5
    
    # Linux GCC 5.4 (RelWithDebInfo)
    - os: linux
      compiler: gcc
      env: CONFIG=RelWithDebInfo CXX_COMPILER=g++-5 C_COMPILER=gcc-5


# Cache external dependencies
cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/deps/install/cmake-${CMAKE_VERSION}

#===---------------------------------------------------------------------------------------------===
#   Installing (external dependencies)
#===---------------------------------------------------------------------------------------------===

install:
  # Create deps dir if not existing
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR}

  # Make sure CXX and C are set correctly
  - if [[ "${CXX_COMPILER}" != "" ]]; then export CXX=${CXX_COMPILER}; fi
  - if [[ "${C_COMPILER}" != "" ]]; then export CC=${C_COMPILER}; fi
  - $CC --version
  - $CXX --version
  
  # Make sure CMAKE_BUILD_TYPE is correctly set
  - if [[ "${CONFIG}" != "" ]]; then export CMAKE_BUILD_TYPE=${CONFIG}; fi

  # Start building external dependencies
  - pushd $(pwd)
  - cd ${DEPS_DIR}

  # Install CMake 3.6.1
  - |
    CMAKE_INSTALL_DIR=${DEPS_DIR}/install/cmake-${CMAKE_VERSION}
    if [[ -z "$(ls -A ${CMAKE_INSTALL_DIR})" ]]; then
     CMAKE_SHORT_VERSION=${CMAKE_VERSION%.*}
     travis_retry wget --quiet                                                                     \
                  https://cmake.org/files/v${CMAKE_SHORT_VERSION}/cmake-${CMAKE_VERSION}.tar.gz
     tar xfz cmake-${CMAKE_VERSION}.tar.gz
     (cd cmake-${CMAKE_VERSION} && ./configure --prefix=${CMAKE_INSTALL_DIR} && make install)
    fi
    export PATH="${CMAKE_INSTALL_DIR}/bin:${PATH}"

  - popd


#===---------------------------------------------------------------------------------------------===
#   Building
#===---------------------------------------------------------------------------------------------=== 

before_script:
  # Setup the X-Server and initialize a virtual display of 1280x1024x16
  - export DISPLAY=:99.0
  - |
    /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile       \
                            --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16
  - sleep 3

  - cmake --version
  - mkdir build

#===---------------------------------------------------------------------------------------------===
#   Testing
#===---------------------------------------------------------------------------------------------=== 

script:
  - pushd $(pwd)
  - cd build


notifications:
  on_success: never
  on_failure: never