dist: trusty
sudo: false

language: c++

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - deadsnakes
    packages:
      - python3.5

      - g++-5
      - gcc-5
      - g++-6
      - gcc-6
      - clang++-3.8
      - clang-3.8 
      
      - libtbb-dev

      # OpenCV deps
      - libjpeg-dev 
      - libpng12-dev 
      - libtiff4-dev 
      - libjasper-dev 

      # glfw3 deps
      - xorg-dev 
      - libglu1-mesa-dev
      - libx11-6
      - libxcursor1
      - libxi6
      - libxinerama1
      - libxrandr2
      - libxxf86vm1

      # backward deps
      - libdw-dev

os:
  - linux

env:
  global:
    - SCRIPT_DIR=${TRAVIS_BUILD_DIR}/scripts/travis
    - CACHE_DIR=${TRAVIS_BUILD_DIR}/deps/install
    - BOOST_VERSION=1.63.0
    - CMAKE_VERSION=3.8.1
    - GLBINDING_VERSION=2.1.1
    - OPENCV_VERSION=3.2.0

jobs:
  include:
    - &prepare_cache_stage
      stage: Prepare Cache
      compiler: gcc
      env: CXX_COMPILER=g++-5 C_COMPILER=gcc-5
      script: |
        bash ${SCRIPT_DIR}/driver-install.sh -i ${CACHE_DIR}                                       \
             -b cmake,boost,glbinding,opencv                                                       \
             -c boost:atomic,chrono,date_time,filesystem,program_options,thread

    - <<: *prepare_cache_stage
      compiler: clang
      env: CXX_COMPILER=clang++-3.8 C_COMPILER=clang-3.8

    # Linux GCC 5.4 (Release)
    - &test_stage
      stage: Test
      script: bash ${SCRIPT_DIR}/driver-test.sh
      compiler: gcc
      env: CONFIG=Release CXX_COMPILER=g++-5 C_COMPILER=gcc-5
    
    # Linux GCC 5.4 (RelWithDebInfo)
    - <<: *test_stage
      compiler: gcc
      env: CONFIG=RelWithDebInfo CXX_COMPILER=g++-5 C_COMPILER=gcc-5

    # Linux GCC 6.3 (Release)
    - <<: *test_stage      
      compiler: gcc
      env: CONFIG=Release CXX_COMPILER=g++-6 C_COMPILER=gcc-6
    
    # Linux GCC 6.3 (RelWithDebInfo)
    - <<: *test_stage      
      compiler: gcc
      env: CONFIG=RelWithDebInfo CXX_COMPILER=g++-6 C_COMPILER=gcc-6

    # Clang 3.8 (Release)
    - <<: *test_stage      
      compiler: clang
      env: CONFIG=Release CXX_COMPILER=clang++-3.8 C_COMPILER=clang-3.8

    # Clang 3.8 (RelWithDebInfo)
    - <<: *test_stage      
      compiler: clang
      env: CONFIG=RelWithDebInfo CXX_COMPILER=clang++-3.8 C_COMPILER=clang-3.8

    # Clang 4.0 (Release)
    - <<: *test_stage      
      compiler: clang
      env: CONFIG=Release CXX_COMPILER=clang++-3.8 C_COMPILER=clang-3.8 CLANG_VERSION=4.0.0

    # Clang 4.0 (RelWithDebInfo)
    - <<: *test_stage      
      compiler: clang
      env: CONFIG=RelWithDebInfo CXX_COMPILER=clang++-3.8 C_COMPILER=clang-3.8 CLANG_VERSION=4.0.0

cache:
  directories:
    - ${CACHE_DIR}/boost-${BOOST_VERSION}
    - ${CACHE_DIR}/glbinding-${GLBINDING_VERSION}
    - ${CACHE_DIR}/opencv-${OPENCV_VERSION}

branches:
  only:
    - master
    
notifications:
  on_success: never
  on_failure: never